"""add_job_observability_fields

Revision ID: a959a0f88633
Revises: b57f49cc814f
Create Date: 2026-08-21 18:48:24.899641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a959a0f88633'
down_revision: Union[str, Sequence[str], None] = 'b57f49cc814f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('processing_duration_ms', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('llm_provider', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('llm_model', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('llm_input_tokens', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('llm_output_tokens', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('llm_total_tokens', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('error_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'error_code')
    op.drop_column('jobs', 'llm_total_tokens')
    op.drop_column('jobs', 'llm_output_tokens')
    op.drop_column('jobs', 'llm_input_tokens')
    op.drop_column('jobs', 'llm_model')
    op.drop_column('jobs', 'llm_provider')
    op.drop_column('jobs', 'processing_duration_ms')
    op.drop_column('jobs', 'processing_started_at')
    # ### end Alembic commands ###
